apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: lb
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.2.10
  ports:
    - name: port-out-wp
      port: 5050
      targetPort: 80
  selector:
    app: wordpress

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: ctn-wordpress
          image: wordpress
          imagePullPolicy: Never
          env:
            - name: WP_DB_NAME
              value: wordpress
            - name: WP_DB_USER
              value: mysql_user
            - name: WP_DB_PASS
              value: mysql_pass
          ports:
            - name: port-in-wp
              containerPort: 80
    metadata:
      labels:
        app: wordpress
  selector:
    matchLabels:
      app: wordpress