services:
  app:
    build: .
    working_dir: /app
    entrypoint: ["npm", "run", "dev"]
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      - db
    deploy:
      resources:
        limits:
          # cpus: '4'
          memory: 4G

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
