apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: lb
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.2.10
  ports:
    - name: port-out-nginx-http
      port: 80
    - name: port-out-nginx-https
      port: 443
    - name: port-out-nginx-ssh
      port: 22
  selector:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    spec:
      restartPolicy: Always
      containers:
      - name: ctn-nginx
        image: nginx
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
          - name: SSH_USER
            value: ssh_user
          - name: SSH_PASS
            value: ssh_pass
    metadata:
      labels:
        app: nginx
  selector:
    matchLabels:
      app: nginx